# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Deploy

on:
  schedule:
    - cron: "41 2 * * 0"  # every Sunday at 02:41 UTC <https://crontab.guru/#41_2_*_*_0>
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: pcrockett/setup-fly@db3872f3719b4ead11b0a1f58cf8cc5a49b7b0ac # v0.1.2
    - name: flyctl deploy
      env:
        MOLLYSOCKET_VERSION: ${{ vars.MOLLYSOCKET_VERSION || 'latest' }}
        FLY_APP: ${{ secrets.FLY_APP }}
        FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
      run: |
        for _ in 1 2; do
          flyctl deploy \
            --app "${FLY_APP}" \
            --config fly.template.toml \
            --build-arg "MOLLYSOCKET_VERSION=${MOLLYSOCKET_VERSION}" \
            --remote-only \
            && break  # break from `for` loop if successful
          sleep 60  # sleep for 1 minute if failed
        done
